defaults: &defaults
  docker:
    - image: circleci/node:8.9.4

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: test
          command: npm test
  cover:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: cover
          command: npm run cover
workflows:
  version: 2
  build-test-and-cover:
    jobs:
      - build
      - test:
          requires:
            - build
      - cover:
          requires:
            - build
