defaults: &defaults
  working_directory: /tmp
  docker:
    - image: circleci/node:8.9.4

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - persist_to_workspace:
          root: workspace
          paths:
            - node_modules
            - test
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: test
          command: npm test
  cover:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: cover
          command: npm run cover
workflows:
  version: 2
  build-test-and-cover:
    jobs:
      - build
      - test:
          requires:
            - build
      - cover:
          requires:
            - build
