version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
          name: install
          command: npm install
  test:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
          name: test
          command: npm test
  coverage:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
          name: coverage
          command: npm run coverage
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - coverage
          requires:
            - build
